### ISSUE TITLE
Changes in specific CC's through midi in are replicated in midi out

### ISSUE THREAD

**Issue by rgbeitor** [amsynth/amsynth#202] opened 2022-03-15 21:34 UTC
### Expected behavior

Expected behavior:
Modified CC's are only sent to midi out  in two situations:
1) Change in GUI (so the controller surface/external software is aware of the change).
2) Change of patch using PC command (again to make the controller surface/external software aware of the change).

Which parameters are affected?
Mostly the ones that have "jumps" programed in the GUI; examples:
OSC1 Waveform, OSC2 Waveform, LFO Waveform, OSC2 SYNC TO OSC1, Filter type, etc.

### Actual behavior

The issue:
I discovered that changing some specific CC's through midi in (controller surface/external software), the change in the controller is sent through midi out in AMsynth.

How I discovered it:
One year ago, I started with a project to create a portable two instances synth in a SOC (orange pi PC). The operation was successful (thank you again for the modifications done to correct the bug in the midi channels response) and I was able to use the thing to produce some nice sounds.

The system includes hardware: Orange pi PC, sound card and controller/sequencer surface (Arturia Beatstep) and software: a real time kernel compiled by hand, two instances of the AMSynth (also compiled by hand to have the latest code), jackd (regular package) and also a python parser programed by me to convert delta CC values form the encoders of the controller surface to absolute CC's in AMSynth. This parser also stores de current values for all the CC's, acting as some kind of "man in the middle".

At that time, I was mapping only a couple of CC's and probably I was lucky! Last month I started to control the remaining CC parameters with the surface and so I discovered the issue.

I don't know if this behavior is a feature or a bug. Expected behavior to me is that midi out informs about the changes only in those two named situations: change in GUI (so the controller surface/external software is aware of the change) and PC command to change the the current patch (again, so the controller surface /external software is aware of the change).

May be there are reasons for this, that I don't know/understand...

Would it be possible to implement that behavior to avoid that those CC's are sent through midi out when midi in CC changes are received?

Feel free to request all the information / testing that you need for this.

And thank you in advance.

### Information

  - Which version of amsynth are you using?
 For the testing I'm using 1.12.2. In Soc the most current version available at the moment of building: 1.12.4
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
 Standalone version.
  - If using amsynth as a plugin, which host application are you using?
 Not applies.
  - Which operating system & version are you using?
Ubuntu Studio 21.10 for testing:
Linux ksora 5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:03:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux.

In the soc Armbian 22.02.0-trunk Focal:
Linux tyl 5.10.100-rt62-sunxi #trunk SMP PREEMPT_RT Thu Mar 3 15:17:21 CET 2022 armv7l armv7l armv7l GNU/Linux

### Steps to reproduce the behavior

Run Jack server.
Run one instance of AMSynth with midi connectivity.
Configure midi CC's for some of the CC's in AMSynth: For example OSC1 Waveform and Filter cutoff parameters.
Connect a midi sniffer (gmidimonitor in my case) in theAMSynth  midi out .
Connect a virtual midi keyboard (for example VMPK) able to send CC's. Configure it with both previously stated Controllers.
Connect the VMPK midi out to AMSynth midi in.
Modify the the OSC1 Waveform controller configured in VMPK and see the midi sniffer screen. You can see the CC midi messages going out (not expected behavior).-
Modify the Filter cutoff controller configured in  VMPK and see the midi sniffer screen. You can see nothing (expected behavior)

![Screenshot_20220315_223258](https://user-images.githubusercontent.com/71669444/158476463-742dd833-68db-44d1-bfa8-58f0c53fbb17.png)

**Comment by rgbeitor** [comment] 2022-03-15 21:36
And as always, thank you for this awesome piece of software.

**Comment by nickdowell** [comment] 2022-03-29 16:46
The issue appears to be that amsynth "remaps" the MIDI CC to its "preferred" representation - i.e. `0` or `127` for an on/off parameter - so that any other value on the input will result in one of those values being sent.

I have created a branch with to prevent this unnecessary output, please let me know if it resolves your issue!

`feature/midi-output-tweak`

**Comment by nickdowell** [comment] 2022-04-09 10:59
Thanks for the feedback :+1: 

I was able to reproduce the unexpected output for normalized values; it was due to a missing call to `round()`
- fixed in 1c8dea8fc59601f456a3427c9f4dd32f36c97cc1

I did not see any problems with MIDI output for regular values... Please try again with the latest fix and you're still seeing issues then it would be helpful to know if it happens only when MIDI input is connected, or if it also is problematic when amsynth is running in isolation sending MIDI to something like `jack_midi_dump`.

If you attach your `~/.config/amsynth/controllers` file then I'll be able to better replicate your controller setup.

**Comment by nickdowell** [comment] 2022-04-12 19:17
Thanks, I need to do a bit more investigation into these "ghost" values / jumpy UI. Are you using ALSA or JACK MIDI input to amsynth?

> 1)Is it possible to export a preset headless (or store in a free slot in bank )? As explained before, I'm using two instances of amsynth in a SOC without screen and sometimes, when you find a nice sound, I would like to be able to save it somehow...

No there's no current way to save a preset without using the UI 🙁

> 2)How works "sample and hold" waveshape?

It's basically a random value that changes every _x_ samples (determined by the shape control). I guess it's kind of like low pass filtered noise except with some digital nastiness!

**Comment by nickdowell** [comment] 2022-04-16 10:15
The "ghost" MIDI output turned out to be caused by an issue with how the GUI was being updated in response to MIDI input.

This should now be fixed in cb38685ba880d4d19541fdd94de80ce90d370561 :tada:

**Comment by rgbeitor** [comment] 2022-04-18 12:11
Hello again.
Answering you in two different posts. First one:


> Thanks, I need to do a bit more investigation into these "ghost" values / jumpy UI. Are you using ALSA or JACK MIDI input to amsynth?

It is Jack MIDI, as far as I remember.

> 
> > 1)Is it possible to export a preset headless (or store in a free slot in bank )? As explained before, I'm using two instances of amsynth in a SOC without screen and sometimes, when you find a nice sound, I would like to be able to save it somehow...
> 
> No there's no current way to save a preset without using the UI slightly_frowning_face
>

:(
Are there plans for the future about this? There could be two options: cli based or internal response to MIDI command. In my case it would be ok just with some kind of auto export preset to file (with "robotic names" like preset001-preset00N) triggered when you send an specific CC or PC MIDI command. I don't know if this should be very complicated to implement, though.

> > 2)How works "sample and hold" waveshape?
> 
> It's basically a random value that changes every _x_ samples (determined by the shape control). I guess it's kind of like low pass filtered noise except with some digital nastiness!

Thanks for the explanation. I thought it could have been some kind of wavetables OSC, in which the oscilator is defined by an specific "shape"...

**Comment by rgbeitor** [comment] 2022-04-18 12:14
> The "ghost" MIDI output turned out to be caused by an issue with how the GUI was being updated in response to MIDI input.
> 
> This should now be fixed in [cb38685](https://github.com/amsynth/amsynth/commit/cb38685ba880d4d19541fdd94de80ce90d370561) tada


Thank you so much.

I'll be checking the new code ASAP (probably in the coming days).

**Comment by rgbeitor** [comment] 2022-04-18 20:51
Hi again.

Finally I was able to test the software. Couldn't resist :)

The ghosts in the midi out are fully gone. I'm still testing the code, but it looks veeeery good.

I was checking the behavior with almost all the CC's that I'm managing -probably all available- with the external control surface... and almost everyone is working as expected, but two:

Filter Decay control CC (assigned by me to CC111) works but it is like "too sensitive". If I change the CC111 value to CC116 for the same Filter Decay control, behavior is perfectly OK.

Another example: Octave control. I have it assigned to CC29. The behavior is also "too sensitive", with small backward jumping (even when I was only moving forward). Again, if  I replace the CC by 116, it works perfectly. Smooth as butter.

Of course the mapping file for CC's is the same that you have.

Could it be that there is some kind of interaction between some "default" values and the user assigned ones?

Last thing: Starting the program, I get this error:

`(amsynth:43364): dconf-WARNING **: 21:22:38.235: unable to open file '/etc/dconf/db/site': Failed to open file “/etc/dconf/db/site”: open() failed: No such file or directory; expect degraded performance
`
I don't know if this is something dependent  of the version of jack that I'm using, but just FYI

One more time, thank you for your help. Is really appreciated.

**Comment by nickdowell** [comment] 2022-04-19 18:13
>The ghosts in the midi out are fully gone. I'm still testing the code, but it looks veeeery good.

Excellent 😅 

>Filter Decay control CC (assigned by me to CC111) works but it is like "too sensitive". If I change the CC111 value to CC116 for the same Filter Decay control, behavior is perfectly OK.
>
>Another example: Octave control. I have it assigned to CC29. The behavior is also "too sensitive", with small backward jumping (even when I was only moving forward). Again, if I replace the CC by 116, it works perfectly. Smooth as butter.
>
>Of course the mapping file for CC's is the same that you have.
>
>Could it be that there is some kind of interaction between some "default" values and the user assigned ones?

This sounds strange. There's nothing special about one CC vs another in amsynth, except that some of the handling of MIDI spec things like bank selection, pan, sustain pedals etc. are disabled when their CCs are mapped to a parameter.

Since the problem appears to be with only certain CCs like 111, could it be that your controller is sending out these small backward jumps for particular encoders? I think it would be worth checking your controller's output in a MIDI monitor to be sure.

Is there more to this "too sensitive" issue than backward jumping?

>Last thing: Starting the program, I get this error:
>
>(amsynth:43364): dconf-WARNING **: 21:22:38.235: unable to open file '/etc/dconf/db/site': Failed to open file “/etc/dconf/db/site”: open() failed: No such file or directory; expect degraded performance 
I don't know if this is something dependent of the version of jack that I'm using, but just FYI

I'm not sure, but this seems to be a GNOME related issue with a possible solution here: https://askubuntu.com/questions/1397205/how-to-solve-dconf-warning-unable-to-open-file-etc-dconf-db-site

**Comment by rgbeitor** [comment] 2022-04-25 13:11
Hi, Nick:

Thank you for your answer.

My comments between lines.

> > The ghosts in the midi out are fully gone. I'm still testing the code, but it looks veeeery good.
> 
> Excellent sweat_smile

Yeap, excellent!

> 
> > Filter Decay control CC (assigned by me to CC111) works but it is like "too sensitive". If I change the CC111 value to CC116 for the same Filter Decay control, behavior is perfectly OK.
> > Another example: Octave control. I have it assigned to CC29. The behavior is also "too sensitive", with small backward jumping (even when I was only moving forward). Again, if I replace the CC by 116, it works perfectly. Smooth as butter.
> > Of course the mapping file for CC's is the same that you have.
> > Could it be that there is some kind of interaction between some "default" values and the user assigned ones?
> 
> This sounds strange. There's nothing special about one CC vs another in amsynth, except that some of the handling of MIDI spec things like bank selection, pan, sustain pedals etc. are disabled when their CCs are mapped to a parameter.
> 
> Since the problem appears to be with only certain CCs like 111, could it be that your controller is sending out these small backward jumps for particular encoders? I think it would be worth checking your controller's output in a MIDI monitor to be sure.
> 
> Is there more to this "too sensitive" issue than backward jumping?
> 
Ok, let me check the configuration of the controllers in the beatstep. All should be the same, but who knows. What is clear is that it is related to the numbering...

Unluckily I need a Windows machine for this (Arturias will), probably during the week.

> > Last thing: Starting the program, I get this error:
> > (amsynth:43364): dconf-WARNING **: 21:22:38.235: unable to open file '/etc/dconf/db/site': Failed to open file “/etc/dconf/db/site”: open() failed: No such file or directory; expect degraded performance
> > I don't know if this is something dependent of the version of jack that I'm using, but just FYI
> 
> I'm not sure, but this seems to be a GNOME related issue with a possible solution here: https://askubuntu.com/questions/1397205/how-to-solve-dconf-warning-unable-to-open-file-etc-dconf-db-site

This is interesting. I'm using KDE plasma...

One more thing. I was still thinking in the possibility of saving the patches (headless) and I found some kind of possible solution. As I have a parser/converter program for the CC's in the middle (main task is converting relative values to absolute values) and I'm keeping a copy of the current status of ALL CC's, I'm planning some kind of export of the current values.

Probably I can "re-inject" those saved values through midi to a amsynth with GUI and there save the values.
Another better possibility is to convert the values to the original amsynth export format, so you can import the patch easily.
A brief look to one of those patch export files, shows that each parameter uses a specific scale. Is there a list of the ranges of the different parameters?

Thank you again for your support!

**Comment by rgbeitor** [comment] 2022-05-07 17:28
Hello

Short update.

I was finally able to find a windows workstation and check the configuration of the Arturia Beatstep. The configuration of the encoders is the same for every one. Same Channel, same "relative" option (for the granularity of the encoder), same mode (control). Only thing that is different is the CC number, as expected.

So, there is no differences in use 111 or 116. Or they shouldn't be.

I will check using another tools to clarify further.

Keep you informed.

**Comment by nickdowell** [comment] 2022-05-08 18:01
Thanks for the update! I'm just wondering whether it could be a subtle hardware difference between the encoders, because I can't see a reason that amsynth would respond differently to those CCs.

**Comment by nickdowell** [comment] 2022-08-14 12:04
Closing as fixed - unexpected MIDI output was fixed in release [1.13.0](https://github.com/amsynth/amsynth/releases/tag/release-1.13.0)

**Closed by nickdowell** 2022-08-14 12:04 UTC
Labels: Type: Bug, Status: Awaiting Feedback
