### ISSUE TITLE
Carla does not load Amsynth LV2 plugin

### ISSUE THREAD

**Issue by thijz** [amsynth/amsynth#60] opened 2017-01-08 21:50 UTC
Hi Nick

i recently started using Carla (by FalkTX) but Carla does not load the Amsynth LV2 plugin
if i start Carla from a terminal i see this during startup :  
```
Error opening file /usr/lib/lv2/amsynth.lv2/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/amsynth.lv2/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/amsynth.lv2/manifest.ttl
```

i am running 1.7.0-1~779~ubuntu16.04 installed from your PPA
OS : ubuntu 16.04,  Carla version 1.9.6 (2.0-beta4)

grtz
Thijs

**Comment by trebmuh** [comment] 2017-01-09 18:04
Hi @thijz : do you have this file on your system?

**Comment by nixxcode** [comment] 2017-01-09 21:52
Strange; can other hosts load the amsynth LV2 plugin?

Jalv would be a good quick test: `jalv.gtk http://code.google.com/p/amsynth/amsynth`

I'm having issues getting Carla to run at all, so cannot yet try to reproduce the issue...

**Comment by thijz** [comment] 2017-01-09 22:05
hi Olivier (it's always the same people i seem to meet ;-) : i just checked and the /usr/lib/lv2/amsynth.lv2/  directory is completely empty  :-S  guess that explains the error message !
Why it is empty is an other question of course ...

@Nick : i tried using jalv and it (obviously) tells me the same thing : .ttl file not found

any ideas ?

**Comment by thijz** [comment] 2017-01-09 22:09
completely off topic, but does the Lv2 version of Amsynth provide midi feedback? (for midi controllers)
i'm not event sure if this is a relevant question for a LV2 plugin !

**Comment by trebmuh** [comment] 2017-01-10 08:04
@thijz yes, linux-audio is still a small world :)

Anyway, how did you install amsynth, package or compilation?

**Comment by thijz** [comment] 2017-01-10 09:56
i installed it from Nick's PPA 
should i try to re-install it, just to see what happens ?
or is there something else i should check before i do this ?

**Comment by trebmuh** [comment] 2017-01-10 10:33
@thijz : I just checked and Nick's package doesn't install it under /usr/lib/lv2/amsynth.lv2/ but under /usr/lib/x86_64-linux-gnu/lv2/amsynth.lv2/ .
As a workaround, you can simlink it (`ln -s`).
It looks to be a packaging issue since my package (for debian Jessie) is putting it in the expected location. ( @nixxcode : certainly because my debian/compat is set to 7 - I don't know if that's the right way or no but it works).

**Comment by thijz** [comment] 2017-01-10 10:49
aha !
i added the /usr/lib/x86_64-linux-gnu/lv2/amsynth.lv2/ path to Carla's 'discovery' path list and ... tadaa !
my fantastic, beloved and indispensable AmSynth is back !!!
i did delete the /usr/lib/lv2/amsynth.lv2/ dir to avoid confusion, but maybe i should have kept it and moved all the stuff from the x86... location to it ?

seems like there is something weird going on with the install of the LV2 plugin, or at least with the creation/selection of the LV2 path

thanks for the help guys!
let me know if/when this gets fixed and i'll be happy to test it  :-)

grtz
Thijs

**Comment by nixxcode** [comment] 2017-01-10 21:15
@thijz thanks for the feedback, I'll let you know when it's ready for testing.

> does the Lv2 version of Amsynth provide midi feedback? (for midi controllers)

No, the LV2 version does not output MIDI.

@trebmuh thanks for the hint!

**Comment by nixxcode** [comment] 2017-01-11 14:19
Fixed in the latest PPA build (installs amsynth in `/usr/lib/lv2/amsynth.lv2` ignoring debian multiarch policy)

Please re-open this issue if it's not resolved for you, @thijz

**Closed by nixxcode** 2017-01-11 14:19 UTC

**Comment by trebmuh** [comment] 2017-01-11 15:20
:+1:

**Comment by thijz** [comment] 2017-01-12 08:35
hi Nick
i uninstalled Amsynth (via synaptic) and this cleaned up the lv2 directorys > OK
then i reinstalled it and the LV2 plugin is now in /usr/lib/lv2/amsynth.lv2/ > OK

thanks for the quick response !

grtz
thijs
