### ISSUE TITLE
config.status: error: po/Makefile.in.in was not created by intltoolize.

### ISSUE THREAD

**Issue by teamblubee** [amsynth/amsynth#108] opened 2017-11-02 17:41 UTC
### Expected behavior
compilation to proceed
### Actual behavior
compilation failure
### Information

  - Which version of amsynth are you using? github latest commit 37f24f2
  - Which build of amsynth are you using? stand-alone application
  - Which operating system & version are you using? FreeBSD

### Steps to reproduce the behavior

  1. ... try to build the program, it fails
This is a bug, here's some more information on it:
https://bugs.launchpad.net/inkscape/+bug/1418943

Can you make the changes to your configure scripts?

**Comment by nickdowell** [comment] 2017-11-18 09:09
I don't have FreeBSD so cannot reproduce this issue or verify which changes are required.

Happy to accept a pull request as long as it doesn't break anything on Linux.

**Comment by teamblubee** [comment] 2017-11-19 17:04
HI

I did some research and found a similar issue on another project in the Debian eco-system. Seem's it's a bug related to GNU makefile options.

Take a look at this issue and solution, would you be able to do something like this?
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=724555

**Comment by nickdowell** [comment] 2017-11-26 08:50
Hi @teamblubee I'm made a change along those lines on the `feature/fix-gettext-intltool` branch - please try it out when you have the time

**Comment by teamblubee** [comment] 2017-12-01 11:17
Hi @nickdowell I was able to build the project and it's successfully Ported to FreeBSD.
https://www.freshports.org/audio/amsynth

Thanks!

**Comment by nickdowell** [comment] 2017-12-01 17:53
Thanks for confirming, I have merged the fix onto `develop`

**Closed by nickdowell** 2017-12-01 17:53 UTC
Labels: build-error
