### ISSUE TITLE
DSSI plugin sticks when playing MIDI sequence

### ISSUE THREAD

**Issue by ondinegreen** [amsynth/amsynth#214] opened 2022-07-07 04:03 UTC
### Actual behavior

When a MIDI sequence is stopped playing in the middle of a note, the note keeps playing and the plugin won't reset. The only way to stop the note playing is restart the sequence and to stop it during a pause.

### Information

  - Which version of amsynth are you using?
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST)
  - If using amsynth as a plugin, which host application are you using?
  - Which operating system & version are you using?

Ubuntu Studio 22.04, amsynth DSSI plugin in Rosegarden version 21.12 ("Cloud Nine"). But this behaviour was the same under Ubuntu Studio 20.04 running in Rosegarden 20.12.

### Steps to reproduce the behavior

  1. Load Rosegarden file with any MIDI sequence playing through the amsynth plugin.
  2. Hit "stop" while a note is playing.

**Comment by nickdowell** [comment] 2022-07-09 10:34
I have been unable to reproduce this issue with either the current or old 1.9.0 version of amsynth that is included with Ubuntu 20.04. Tested with Rosegarden 19.12 and 22.06, using a simple project - [amsynth.rg.zip](https://github.com/amsynth/amsynth/files/9076294/amsynth.rg.zip).

Which version of amsynth are you using?

Could you create and attach a minimal sample project that demonstrates the problem?

Thanks!

**Comment by nickdowell** [comment] 2022-09-25 16:48
Hi @ondinegreen can you provide any further information to help me reproduce the issue?

**Comment by nickdowell** [comment] 2023-01-28 11:15
Closing because I cannot repro, will reopen if further instructions can be provided.

**Closed by nickdowell** 2023-01-28 11:15 UTC
Labels: Type: Bug, Status: Cannot Reproduce
