### ISSUE TITLE
send midi on controller change

### ISSUE THREAD

**Issue by georgkrause** [amsynth/amsynth#39] opened 2016-09-22 12:31 UTC
if i got this right amsynth sends controller values over midi only when "Send settings to MIDI" is triggered. in order to use a midi controller even if i change presets, i need the changes to be sent when the controllers are changed. so it would be nice if the "Send settings to MIDI"-function ist triggered when i load a new preset. one step further it would be great if any controller change would be sent per midi on change.

**Comment by nixxcode** [comment] 2016-09-22 12:57
That is true for the current stable release (1.6.4)

The latest code in git, though, sends MIDI CCs as soon as parameters are changes on the GUI or presets are loaded. The "Send settings to MIDI" menu item was also removed.

This issue is a duplicate of #21

**Closed by nixxcode** 2016-09-22 12:57 UTC

**Comment by georgkrause** [comment] 2016-09-22 13:00
sorry for that @nixxcode :(

**Comment by nixxcode** [comment] 2016-09-22 13:03
No problem @georgkrause  it just reinforces that it is a good feature / change request 😃 

Let me know if it does not seem to be working right

**Comment by georgkrause** [comment] 2016-09-22 13:15
ill try when i am at home ;)
