### ISSUE TITLE
Enable microtonal in presets

### ISSUE THREAD

**Issue by nobrakal** [amsynth/amsynth#19] opened 2016-06-06 19:28 UTC
Hi,

I am always with my idea of micro-tuning. I work with amsynth in a raspberry with a master keyboard, and, with that setup, I just can't change my tuning during a song. I have to shutdown all my things, change a file on a SD and reload everything. So, I was thinking about how change that...
One solution will be to work with SysEx midi and doing some midi-vodoo to implement this idea through midi signal: When a signal is received, it change the scale. But this is not very useful, you will have to specify a list of scale, and change a lot the code.

The other solution, much better I think was to implement a new parameter in the presets, a scale, like a path to a different tuning file (or, much better I think, include this file in the preset). Now you can change the scale trough midi (by changing the preset), and adapt your preset according to the scale.
Even better, adding a note reference (different than a A 440), because doing a 16-tone per octave only in 440 is not very funny...

It will need some adjustment, but what do you think about that ?

**Comment by nixxcode** [comment] 2016-06-13 19:35
I've never used micro-tuning myself so I'm not really sure what the best way to do this is. Are there any other synth plugins that do a good job of supporting micro-tuning and how do they implement it?

I understand the desire to be able to change the tuning when running on a pi or other embedded / headless device.

Should the micro-tuning setting really be stored and recalled as part of a preset, though?

My current thinking is that it might be better to hard-code a particular cc, nrpn or sysex to control this - one message to specify which tuning map to use, and another message to change the note reference. It would also be possible to send the contents of a tuning map file over sysex and have amsynth load it.

What is your MIDI controller capable of sending?

**Comment by nobrakal** [comment] 2016-06-14 08:35
I only know zynaddsubfx for doing microtonal, but I don't know if they implement live-change of scales or change the note reference...

Yes, hard-coding is a better idea, you are right! I am currently using the UMX250 of Behringer, and after reading the doc, it only seem able to send a cc or nrpn change (I didn't know the last one). Their guide mention sysex, but it don't say how to use it. Sending a whole file through sysex ? Would be terrific, but need an also terrific keyboard, I think...
I discover all this things now, so I don't know what is the best solution, but I was thinking about using the instr-change command. Why not indicate by a CC button that the next message will not be a command to change the current instrument, but change the tuning. It allow us to manage at least 127 different scales, and use the current system of bank.

For the note reference, a particular cc seems the best, with a potentiometer for example.

Thank you for your help and your interest :)

**Comment by suhr** [comment] 2016-08-19 09:42
@nixxcode See [MIDI Tuning Standard](http://www.microtonal-synthesis.com/MIDItuning.html) and [Scala file format](http://www.huygens-fokker.org/scala/scl_format.html).

Note that there's only 128 notes in midi while some tunings have [31 notes](http://31et.com/) in octave.

> Are there any other synth plugins that do a good job of supporting micro-tuning and how do they implement it?

Pianoteq, Zynaddsubfx and [Xen-Arts synths](http://xen-arts.net/)

**Comment by nixxcode** [comment] 2016-08-28 10:08
Thanks @suhr for the link about MIDI Tuning Standard - I am now planning to implement support for the Tuning program change registered parameter number controller message.

**Comment by SeanArchibald** [comment] 2017-06-04 23:47
Glad to see that this was already requested. I'm struggling to find VST instruments on Linux that can support microtonality. Is there still any possibility of seeing support for microtonal tunings in the future?

**Comment by nixxcode** [comment] 2017-06-05 16:07
@SeanArchibald sure, support could be added for switching between tunings in the plugins via the GUI or via MIDI messages. If you are able to test and give feedback on the changes once ready that would be greatly appreciated.

**Comment by SeanArchibald** [comment] 2017-06-05 16:40
Yes I'm available to test and offer feedback.

Did you decide on which method you would use for microtuning - was it MIDI Tuning Standard? MIDI Tuning Standard is pretty great, although the only thing that worries me is that many DAWs strip out MIDI SYSEX before it reaches the plugin (I'm looking at you, Ableton Live).

**Comment by suhr** [comment] 2017-06-05 17:09
> many DAWs strip out MIDI SYSEX before it reaches the plugin

When you can set the tuning in the synth ui, this is a minor issue.

> If you are able to test and give feedback on the changes once ready that would be greatly appreciated.

I also would like to test it.

**Comment by nixxcode** [comment] 2017-06-05 18:19
The current plan is to
* Add a directory to place your tuning files for quick access - e.g. `~/.amsynth/tuning`
* Extend the plug-in's right-click menu to add tuning options
* Add support for "[tuning program change]()" MIDI messages. These are sent using registered parameter number (RPN) controller messages, not sysex, so should not be filtered out. This will be especially useful for operating amsynth in headless mode.

```
Tuning program change

Bn 64 00 65 03 06 tt (data entry)
Bn 64 00 65 03 60 7F (data increment)
Bn 64 00 65 03 61 7F (data decrement)
                     
n = basic channel number
tt = tuning program number from 1 to 128
```

**Comment by nixxcode** [comment] 2017-06-07 16:30
After reading [this article about Microtonality in Falcon](http://soundbytesmag.net/microtonality-in-falcon/) and [this article following up on it](http://xen-arts.net/microtonality-in-falcon-soundbytes-review-by-warren-burt/) I am not so sure my previous plan is a good one because switching between `.scl` files without also taking to account key mappings (`.kbm`) is not all that useful. 

What seems to be needed is a UI to combine SCLs and KBMs into "tuning programs" that could then be selected by MIDI messages or a UI menu. This is quite a bit more work than my original plan.

Adding the ability to load `.scl` and `.kbm` files from the plugins (replicating the stand-alone app's functionality) is straightforward and is almost ready to test.

Hoping to hear opinions from those of you that use alternate tunings, though, because I don't!

**Comment by suhr** [comment] 2017-06-07 18:04
U-he synths use .tun files. Tun files specify pitches for each MIDI note, so it's like scl+kbm combined.
It is single channel though, but when you can set a different tuning for each channel, this is not an issue.

**Comment by SeanArchibald** [comment] 2017-06-07 20:51
@nixxcode You're quite correct that supporting .scl without .kbm is not that useful. They really should be supported together. The xen-arts article you posted makes it very clear why this is so.

I agree with @suhr that .tun files are a good alternative to .scl/.kbm. As someone in the field who uses alternative tunings, I'm quite happy that most of my synths accept .tun files. It looks like .tun could fit in well with your original plan.

If you scroll down this page a bit, you'll see an option to download source code for parsing .tun data: http://www.mark-henning.de/am_downloads_eng.php

It's interesting that you plan to support the loading of multiple tunings at once - and allow the user to switch between them with MIDI messages. I don't know of any other synth that currently supports this. It would blow my mind. Actually here's what would blow my mind - if I could interpolate between two different tunings in a continuous fashion, such that my tuning could gradually morph over time from one to another, I would just about go insane with joy.

That being said, I almost always write a piece in one tuning without changing it half way through. So if it's only possible to support one tuning at a time, I will still be very grateful for that.

Many thanks!

**Comment by nixxcode** [comment] 2017-06-10 17:43
There is now **experimental** support for loading .scl and .kbm files in the plugins 😎 

Please check out the [feature/plugin-tuning-menu](https://github.com/amsynth/amsynth/tree/feature/plugin-tuning-menu) branch if you're interested in trying it out.
```
git fetch
git checkout feature/plugin-tuning-menu
```

Known issues:
* LV2 & VST plugins do not yet save / restore the tuning setup, so will revert to default when closing and opening a session

**Comment by suhr** [comment] 2017-06-10 23:58
31et.scl loads fine, and so does 31et.kbm. Everything works as expected.

...except reverb. But it is just the same as before also Calf Reverb fixes it anyway.

Anyway, thank you for the nice little *microtonal* synth!

**Comment by nixxcode** [comment] 2017-06-11 08:26
There was a bug with LV2 controls not working properly, this is fixed now.
Also the LV2 plug-in now saves & restores tuning setup.

@suhr I've not had any reports of reverb not working - can you tell me what the problem is?

**Comment by suhr** [comment] 2017-06-11 12:13
> I've not had any reports of reverb not working - can you tell me what the problem is?

It *is* working. It is just rather *low-fi* compared to any other reverbs I know.

**Comment by SeanArchibald** [comment] 2017-06-12 10:53
I haven't done any of this configure and make stuff before, I will try to figure it out today. If there's an easy way to get the VST or LV2 working please let me know. After I find out how to load amsynth in an LV2/VST host I will start testing amsynth will all kinds of microtonal tunings!

**Comment by SeanArchibald** [comment] 2017-06-12 11:32
I managed to build and install this. When running amsynth as a standalone application, I was able to load two different .scl files which sounded as I would expect. This is looking very positive!

I want to get this running as a Linux VST before I do more testing with different microtunings and also test that the keyboard mapping works as expected.

So far I was able to run amsynth in a VST host, everything works fine except I can't get to the menu which allows me to load a tuning/mapping file. Any ideas?

**Comment by suhr** [comment] 2017-06-12 12:07
> Any ideas?

Right click.

**Comment by SeanArchibald** [comment] 2017-06-12 12:13
Tried that - it gives me a list of banks but no option to load microtuning. What am I missing?

**Comment by suhr** [comment] 2017-06-12 12:20
To me it shows this menu:

```
Preset >
Tuning >
```

**Comment by SeanArchibald** [comment] 2017-06-12 13:27
I see 21 options on the menu, 'User Bank', 'BriansBank' (1-19), amsynth factory..

**Comment by suhr** [comment] 2017-06-12 14:35
That's what in `Preset >`. Are you sure you don't use an old VST plugin?

**Comment by SeanArchibald** [comment] 2017-06-12 15:35
It turns out I forgot to checkout the feature branch before I did the build part. Anyway, fixed!

I have now tested a few tunings and mappings, mostly everything works. I had trouble tuning to the Bohlen-Pierce scale. I get an error "Failed to load new tuning. - Reading the tuning file failed for some reason. Make sure your file has the correct format and try again" with the following Scala file:

`! 13 equal divisions of 3_1.scl
! Created using Scale Workshop 0.5
!
13 equal divisions of 3/1
 13
!
 146.304231
 292.608462
 438.912693
 585.216923
 731.521154
 877.825385
 1024.129616
 1170.433847
 1316.738078
 1463.042308
 1609.346539
 1755.650770
 1901.955001
`

The Bohlen-Pierce scale repeats at the perfect twelfth (3/1) instead of the octave (2/1).

I also tried to tune amsynth to Wendy Carlos' Beta scale, which divides the perfect fifth (3/2) into 11 equal steps. This one caused the same error as above. I suspect that amsynth's implementation doesn't support non-octave scales. Does amsynth assume that the user's tuning repeats at the octave? Because many tunings repeat at intervals other than the octave.

amsynth will crash if you try to play a note that is too high. For example if you load a .kbm file that sets the tuning very low:

`! Template for a keyboard mapping
!
! Size of map. The pattern repeats every so many keys:
12
! First MIDI note number to retune:
0
! Last MIDI note number to retune:
127
! Middle note where the first entry of the mapping is mapped to:
5
! Reference note for which frequency is given:
5
! Frequency to tune the above note to
440.0
! Scale degree to consider as formal octave (determines difference in pitch
! between adjacent mapping patterns):
12
! Mapping.
! The numbers represent scale degrees mapped to keys. The first entry is for
! the given middle note, the next for subsequent higher keys.
! For an unmapped key, put in an "x". At the end, unmapped keys may be left out.
0
1
2
3
4
5
6
7
8
9
10
11
`

That mapping should set MIDI note 5 to 440.0Hz. So if you then play a note much higher up, amsynth will instantly crash.

**Comment by SeanArchibald** [comment] 2017-06-13 11:11
You can reproduce the crashing even without using a keyboard mapping. Just choose a very compact scale like 5-EDO and then play one of the high MIDI notes.

**Comment by nickdowell** [comment] 2024-06-01 10:15
I think the recently added MTS-ESP support https://github.com/amsynth/amsynth/issues/218 supports a lot of the use cases here.

The plug-in versions of amsynth also now remember which scl & kbm files were loaded.

After more experience using other synth plug-ins that support micro-tonal, I do not think micro-tuning settings should be saved as part of presets.

Note these new features are on the `develop` branch but not in an official release yet.

**Closed by nickdowell** 2024-06-01 10:15 UTC
Labels: Type: Enhancement
