### ISSUE TITLE
Click at the start of a note

### ISSUE THREAD

**Issue by pawa75** [amsynth/amsynth#196] opened 2021-11-14 16:56 UTC
### Expected behavior
A preset should sound the same the first or second time and more when a key is hit, with the exception to portamento, if the key is hit after the sound has toned out. 
### Actual behavior
Some presets have a click when a key is hit the first time in compare to the second time and more. For an example, if I play the note C for the first time after a selected sound, there is a click on some presets. If I when play D, it's the same with an undesired click. But if I then, after the sound has toned out, play C again, there is no click in the beginning of the sound. 
### Information

  - Which version of amsynth are you using? 1.12.2
  - Which build of amsynth are you using? (stand-alone application, LV2, DSSI, VST) Stand-alone application
  - If using amsynth as a plugin, which host application are you using?
  - Which operating system & version are you using? Fedora 35, but it was the same on previous versions for example 33 and 34. 

### Steps to reproduce the behavior

  1. Play BriansBank01 11: Pianola2, 60: warm2 ; from a Midi Keybord
  2. ...

**Comment by pawa75** [comment] 2021-12-01 20:11
I'm using Fedora 35, maybe it's something with Pipewire.

**Comment by nickdowell** [comment] 2021-12-23 10:36
Hi @pawa75!

I find that with Pianola2 I can reproduce the click at the start of the note almost every time (with the same note) by waiting a second or two between notes - is it the same for you?

I also found that reducing the master volume sort of fixes it, although that's not a great solution.

The problem seems to be due to the signal getting clipped, and I've pushed a branch with a tweak that fixes it for me - `feature/fix-attack-click`. If you're able to try out that branch and let me know if it fixes it for you, that would be very helpful.

Thanks!

**Comment by pawa75** [comment] 2021-12-23 11:08
Thanks. I'm excited to try it out. I'll do that when I'm home again after
Christmas.

Den tors 23 dec. 2021 11:36Nick Dowell ***@***.***> skrev:

**Comment by pawa75** [comment] 2021-12-26 22:11
Hi, I've now clone the repository.
git clone https://github.com/amsynth/amsynth

I'm just writing this so you know how I did it, and maybe as a guide if somebody else want to try your fix by to compiling Amsynth on Fedora.
I've installed the following packages on Fedora 35.
pipewire-jack-audio-connection-kit-devel
alsa-lib-devel
gtk2-devel
autoconf-archive

I had to run autoreconf -f after reboot to make the configure script to work.

Then I removed amsynth and install the new build, started amsynth with pw-jack /usr/local/bin/amsynth

I'm sorry to say that there is still a click the first time I hit a key on the midi keyboard, but not the second time, even if I wait for 3-4 seconds. I've made a recording with jack_capture, playing BriansBank01 11: Pianola2

https://drive.google.com/file/d/1gNxvqNdejBggwVjqOSZnYo6EcgpcjK0I/view?usp=sharing

**Comment by nickdowell** [comment] 2021-12-28 10:30
Hi @pawa75 thanks for testing this - some further investigation revealed the real problem behind the inconsistent sounds when playing a note for the first time.

I'm fairly confident it's fixed now on the same branch - if you do a `git pull` I hope you'll agree!

**Comment by pawa75** [comment] 2021-12-29 00:06
Yes, now the click on the first note is gone. I'm very grateful for that. But a new problem, that did not existed before, is that the volume knob don't work. It makes no change to the volume any longer, making some of the presets too loud and sounding compressed when more than one note is played at the same time. I don't know if it has do with LASH support not being activated. I have LASH installed, but there is no lash-devel package in Fedora. The volume knob works in the version of amsynth that can be installed from the Fedora's repository.

+------------------------------------------------------- amsynth 1.12.2
|
| GTK version........................................... : 2.24.33
| Build with GUI support................................ : yes
|
| Build with OSS support................................ : yes
| Build with ALSA support............................... : yes
| Build with JACK support............................... : yes
| Build with JACK MIDI support.......................... : yes
| Build with JACK session support....................... : yes
| Build with LASH support............................... : no
| Build with Non Session Manager support................ : no
| Build DSSI plugin..................................... : yes
| Build DSSI GUI........................................ : no
| Build LV2 plugin...................................... : yes
| Build VST plugin...................................... : yes
|
| Generate man pages using pandoc....................... : no

**Comment by nickdowell** [comment] 2021-12-29 11:50
Sorry about that - the volume issue should be fixed now :+1:

**Comment by pawa75** [comment] 2021-12-29 23:23
Thanks for fixing it! Everything seems to be OK now!

**Comment by nickdowell** [comment] 2021-12-30 11:34
Thanks for confirming :-)

**Closed** 2021-12-30 11:52 UTC
Labels: Type: Bug, Status: Awaiting Feedback
